### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-xiaomi-robot-vacuum: Cannot find module 'miio'

### ISSUE THREAD

**Issue by BonRm** [seikan/homebridge-xiaomi-mi-robot-vacuum#26]
hello, i'm getting this errors, anyone can help me?

before adding the robot accesory everything was working good

====================
[11/20/2019, 11:35:17 AM] ERROR LOADING PLUGIN homebridge-xiaomi-robot-vacuum:
[11/20/2019, 11:35:17 AM] Error: Cannot find module 'miio'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object. (/usr/local/lib/node_modules/homebridge-xiaomi-robot-vacuum/index.js:3:14)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[11/20/2019, 11:35:17 AM] ====================
Error: The requested accessory 'MiRobotVacuum' was not registered by any plugin.
at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[11/20/2019, 11:35:18 AM] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: xxxx
[11/20/2019, 11:35:18 AM] Got SIGTERM, shutting down Homebridge...
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service RestartSec=3s expired, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 42.
Stopped Homebridge.
Started Homebridge.
[11/20/2019, 11:35:27 AM] Loaded config.json with 1 accessories and 3 platforms.
[11/20/2019, 11:35:27 AM] ---
[11/20/2019, 11:35:27 AM] Loaded plugin: homebridge-config-ui-x
[11/20/2019, 11:35:27 AM] Registering platform 'homebridge-config-ui-x.config'
[11/20/2019, 11:35:27 AM] ---
[11/20/2019, 11:35:27 AM] Loaded plugin: homebridge-mi-aqara-fakegato
[11/20/2019, 11:35:27 AM] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[11/20/2019, 11:35:27 AM] ---
[11/20/2019, 11:35:27 AM] Loaded plugin: homebridge-platform-orvibo
[11/20/2019, 11:35:27 AM] Registering platform 'homebridge-platform-orvibo.Orvibo'
[11/20/2019, 11:35:27 AM] ---
[11/20/2019, 11:35:27 AM] ====================
[11/20/2019, 11:35:27 AM] ERROR LOADING PLUGIN homebridge-xiaomi-robot-vacuum:
[11/20/2019, 11:35:27 AM] Error: Cannot find module 'miio'
.......
[11/20/2019, 11:35:58 AM] Loading 3 platforms...
[11/20/2019, 11:35:58 AM] [Config] Initializing config platform...
[11/20/2019, 11:35:58 AM] [Config] Running in Standalone Mode.
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO]**************************************************************
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO] MiAqaraPlatform v0.8.6 By YinHang
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO] GitHub: https://github.com/YinHangCode/homebridge-mi-aqara
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO] QQ Group: 107927710
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO]**************************************************************
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO]start success...
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO]config gateways: xxxxxxxxxxxx
[11/20/2019, 11:35:58 AM] [MiAqaraPlatform] [INFO]binding to the default interface
[11/20/2019, 11:35:58 AM] [Orvibo] Initializing Orvibo platform...
[11/20/2019, 11:35:58 AM] Loading 1 accessories...
[11/20/2019, 11:35:58 AM] Error: The requested accessory 'MiRobotVacuum' was not registered by any plugin.

this id my config file:

{
"bridge": {
"name": "HOOBS",
"username": "xx.xx.xx.xx:30",
"port": xxxxx,
"pin": "0xx-xx-xx"
},
"description": "This file is used for plugin configuration.",
"accessories": [
{
"accessory": "MiRobotVacuum",
"name": "Vacuum Cleaner",
"model": "rockrobo.vacuum.v1",
"ip": "192.1x.x1.1x",
"token": "6xxxxxxxxxxxxxxxxxxxxxxa54",
"showDock": true,
"enablePause": true
}
],
"platforms": [
{
"name": "Config",
"port": 8080,
"auth": "form",
"theme": "amber",
"sudo": true,
"standalone": true,
"restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
"temp": "/sys/class/thermal/thermal_zone0/temp",
"log": {
"method": "custom",
"command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
},
"platform": "config"
},
{
"platform": "MiAqaraPlatform",
"gateways": {
"f0xxxxxxxa91": "FA8xxxxxxxxxx283"
}
},
{
"platform": "Orvibo"
}
]
}

**Comment by Matzushub** [comment]
I got the same message. Did you solve it by now? My guess is that the MIio module is not installed or not globally.

**Comment by kavallaris** [comment]
same here! any idea how to solve this?
